package edu.acc.j2ee.capstone.model;
// Generated Jul 27, 2014 2:59:38 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Frameorders generated by hbm2java
 */
@Entity
@Table(name="FRAMEORDERS"
    ,schema="APP"
)
public class Frameorders  implements java.io.Serializable {


     private int frameid;
     private String ordername;
     private String mat;
     private int matwidth;
     private String frametype;
     private int jobwidth;
     private int jobheight;
     private int customerid;

    public Frameorders() {
    }

    public Frameorders(int frameid, String ordername, String mat, int matwidth, String frametype, int jobwidth, int jobheight, int customerid) {
       this.frameid = frameid;
       this.ordername = ordername;
       this.mat = mat;
       this.matwidth = matwidth;
       this.frametype = frametype;
       this.jobwidth = jobwidth;
       this.jobheight = jobheight;
       this.customerid = customerid;
    }
   
     @Id 

    
    @Column(name="FRAMEID", unique=true, nullable=false, precision=15, scale=0)
    public int getFrameid() {
        return this.frameid;
    }
    
    public void setFrameid(int frameid) {
        this.frameid = frameid;
    }

    
    @Column(name="ORDERNAME", length=35)
    public String getOrdername() {
        return this.ordername;
    }
    
    public void setOrdername(String ordername) {
        this.ordername = ordername;
    }

    
    @Column(name="MAT", length=40)
    public String getMat() {
        return this.mat;
    }
    
    public void setMat(String mat) {
        this.mat = mat;
    }

    
    @Column(name="MATWIDTH", length=10)
    public int getMatwidth() {
        return this.matwidth;
    }
    
    public void setMatwidth(int matwidth) {
        this.matwidth = matwidth;
    }

    
    @Column(name="FRAMETYPE", length=40)
    public String getFrametype() {
        return this.frametype;
    }
    
    public void setFrametype(String frametype) {
        this.frametype = frametype;
    }

    
    @Column(name="JOBWIDTH", length=25)
    public int getJobwidth() {
        return this.jobwidth;
    }
    
    public void setJobwidth(int jobwidth) {
        this.jobwidth = jobwidth;
    }

    
    @Column(name="JOBHEIGHT", length=20)
    public int getJobheight() {
        return this.jobheight;
    }
    
    public void setJobheight(int jobheight) {
        this.jobheight = jobheight;
    }

    
    @Column(name="CUSTOMERID", length=25)
    public int getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(int customerid) {
        this.customerid = customerid;
    }




}


