package edu.acc.j2ee.capstone.model;
// Generated Jul 27, 2014 2:59:38 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Moulding generated by hbm2java
 */
@Entity
@Table(name="MOULDING"
    ,schema="APP"
)
public class Moulding  implements java.io.Serializable {


     private String id;
     private String imagelink;
     private String name;
     private byte width;
     private String color;

    public Moulding() {
    }

    public Moulding(String id, String imagelink, String name, byte width, String color) {
       this.id = id;
       this.imagelink = imagelink;
       this.name = name;
       this.width = width;
       this.color = color;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=20)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="IMAGELINK", nullable=false, length=20)
    public String getImagelink() {
        return this.imagelink;
    }
    
    public void setImagelink(String imagelink) {
        this.imagelink = imagelink;
    }

    
    @Column(name="NAME", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="WIDTH", nullable=false, precision=10, scale=0)
    public byte getWidth() {
        return this.width;
    }
    
    public void setWidth(byte width) {
        this.width = width;
    }
    
    @Column(name="COLOR", nullable=false, length=30)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


